# **Ejercicios de pair programming Módulo 2 Sprint 1**
## **NumPy: Lección 1**
### **Introducción a NumPy**

---

In [1]:
import numpy as np

1. Cread tres arrays: de una, dos y tres dimensiones.
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas en algunos casos.
    
    📌 Nota
    - El array de 2 dimensiones debe ser de 2 filas y 3 columnas
    - El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [2]:
unidimensional = np.random.randint(1,10, (3))
unidimensional

array([1, 8, 3])

In [4]:
bidimensional = np.random.randint(1,10, (2,3))
bidimensional

array([[6, 9, 6],
       [4, 8, 8]])

In [6]:
multidimensional = np.random.randint(1,10, (2,3,5))
multidimensional

array([[[5, 2, 8, 9, 9],
        [3, 6, 5, 6, 3],
        [7, 1, 6, 8, 6]],

       [[9, 7, 5, 7, 3],
        [4, 2, 4, 9, 3],
        [7, 5, 9, 1, 6]]])

2. Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [8]:
""" """
def propiedades_array(array): 

    print(array)
    return f"Tiene forma de {array.shape}, su tamaño es de {array.size} elemento/s, tiene {array.ndim} dimension/es y el tipo de dato que contiene es {array.dtype}"

In [9]:
propiedades_array(unidimensional)

[1 8 3]


'Tiene forma de (3,), su tamaño es de 3 elemento/s, tiene 1 dimension/es y el tipo de dato que contiene es int64'

In [10]:
propiedades_array(bidimensional)

[[6 9 6]
 [4 8 8]]


'Tiene forma de (2, 3), su tamaño es de 6 elemento/s, tiene 2 dimension/es y el tipo de dato que contiene es int64'

In [11]:
propiedades_array(multidimensional)

[[[5 2 8 9 9]
  [3 6 5 6 3]
  [7 1 6 8 6]]

 [[9 7 5 7 3]
  [4 2 4 9 3]
  [7 5 9 1 6]]]


'Tiene forma de (2, 3, 5), su tamaño es de 30 elemento/s, tiene 3 dimension/es y el tipo de dato que contiene es int64'

3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas.

In [14]:
matriz = np.identity(3)
matriz

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [16]:
matriz_unos = np.ones_like(multidimensional)
matriz_unos

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

5. Es el momento de hacer algunas operaciones entre arrays:
 - ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?


In [ ]:
#No se pueden sumar porque no tienen la misma forma. Si no es así, no se puede operar entre arrays independientemente de las dimensiones. 

 - En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.


In [24]:
nueva_matriz = np.identity(3)
nueva_matriz

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
suma_matrices = np.add(matriz, nueva_matriz)
suma_matrices

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

 - Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.


In [27]:
mul_matrices = np.multiply(matriz, nueva_matriz)
mul_matrices

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 - Dividid las dos matrices

In [29]:
div_matrices = np.subtract(matriz, nueva_matriz)
div_matrices

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])