# **Ejercicios de pair programming Módulo 2 Sprint 1**
## **NumPy: Lección 4**
### **Conjuntos y distribuciones aleatorias**

In [1]:
import numpy as np

1. ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [2]:
np.random.seed(1)
a1 = np.random.random_sample((2,4))
a1

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01]])

In [3]:
np.random.seed(1)
a2 = np.random.random_sample((2,4))
a2

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01]])

2. Cread los siguientes arrays:

- Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

- Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

In [5]:
uniforme = np.random.uniform(0, 10, (2,3,5)).round()
uniforme

array([[[ 0.,  8., 10.,  7.,  3.],
        [ 8.,  1.,  4.,  9.,  3.],
        [ 3.,  1.,  0.,  7.,  2.]],

       [[ 3.,  5.,  1.,  6.,  1.],
        [ 6.,  7.,  1.,  4.,  7.],
        [ 4.,  0.,  5.,  7.,  5.]]])

3. En esta lección hemos aprendido algunos métodos de teórias de conjuntos.
   Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:

    - Elementos comunes entre los dos arrays
    - Unión de los dos arrays
    - ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores   númericos
    
⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?


4. Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.

    - Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.
    - Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.
    - Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.
    - Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.
    - ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.