# **Ejercicios de pair programming Módulo 2 Sprint 1**
## **NumPy: Lección 3**
### **Operaciones estadísticas y matemáticas**

In [1]:
import numpy as np

1. Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed:


In [2]:
array = np.random.random_sample((2,3,5)).round(1)
array

array([[[0.3, 0.6, 0.2, 0.2, 0.3],
        [0.6, 0. , 0.8, 0.9, 0.6],
        [0.6, 0.4, 0.8, 0.6, 0.1]],

       [[0.8, 0.5, 0.1, 0.8, 0.6],
        [0.7, 0.4, 0.6, 0.3, 0.8],
        [0.9, 0.5, 0.4, 0.7, 0.5]]])

2. Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.


In [3]:
array_mean = np.mean(array).round(1)
array_mean

0.5

3. Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.


In [4]:
array_max = np.max(array).round(1)
array_max

0.9

4. Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.


In [5]:
array_min = np.min(array).round(1)
array_min

0.0

5. Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.


In [6]:
array2 = np.empty((2,3,5), dtype=str)
array2

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".

In [7]:
#Las condiciones max y min tienen que ir al principio de la iteración porque si no, al cumplir el 
# valor una de las condiciones no continuaría chequeando las demás. 

for matriz in range(array.shape[0]):
    for fila in range(array.shape[1]):
        for elem in range(array.shape[2]):
            if array[matriz, fila, elem] == array_max:
                array2[matriz, fila, elem] = "D"
            elif array[matriz, fila, elem] == array_min:
                array2[matriz, fila, elem] = "E"
            elif array[matriz, fila, elem] == array_mean:
                array2[matriz, fila, elem] = "A"
            elif array[matriz, fila, elem] > array_mean:
                array2[matriz, fila, elem]= "B" 
            elif array[matriz, fila, elem] < array_mean:
                array2[matriz, fila, elem] = "C"

In [8]:
array2

array([[['C', 'B', 'C', 'C', 'C'],
        ['B', 'E', 'B', 'D', 'B'],
        ['B', 'C', 'B', 'B', 'C']],

       [['B', 'A', 'C', 'B', 'B'],
        ['B', 'C', 'B', 'C', 'B'],
        ['D', 'A', 'C', 'B', 'A']]], dtype='<U1')


```python
# a modo de ejemplo. Si tenemos el siguiente array
[[[0.4, 0.7, 0.2, 0.9, 0.2],
    [0.1, 0.9, 0.6, 0.1, 0.2],
    [1. , 0.2, 0.1, 0.8, 0.3]],

   [[0. , 0.3, 0.4, 0.5, 0.1],
    [0.5, 0.7, 0.9, 0. , 0.8],
    [0.5, 0.3, 0.5, 0.8, 0.1]]])

# sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es 0.0

# nuestro array vacío debería quedar como este: 
[[["A", "B", "C", "B", "C"],
    ["C", "B", "B", "C", "C"],
    ["D" , "C", "C", "B", "C"]],

   [["E" , "C", "A", "B", "C"],
    ["B", "B","B", "E" , "B"],
    ["B", "C", "B", "B", "C"]]])
```
💡 Pista 💡 Tendréis que iterar por el array y cambiar los valores de la matriz vacía. Para eso tendremos que usar distintos condicionales.


6. Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.


In [9]:
array3 = np.empty(30, dtype=int)
array3

array([4599075939470750515, 4603579539098121011, 4596373779694328218,
       4596373779694328218, 4599075939470750515, 4603579539098121011,
                         0, 4605380978949069210, 4606281698874543309,
       4603579539098121011, 4603579539098121011, 4600877379321698714,
       4605380978949069210, 4603579539098121011, 4591870180066957722,
       4605380978949069210, 4602678819172646912, 4591870180066957722,
       4605380978949069210, 4603579539098121011, 4604480259023595110,
       4600877379321698714, 4603579539098121011, 4599075939470750515,
       4605380978949069210, 4606281698874543309, 4602678819172646912,
       4600877379321698714, 4604480259023595110, 4602678819172646912])

En este caso:
- Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1
- Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2
- Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.
Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [16]:
contador = 0
for matriz in array2:
    for fila in matriz:
        for elem in fila:
            if elem == "A" or elem == "B":
                 array3[contador]= 1
            elif elem == "C" or elem == "D":
                array3[contador] = 2
            else: 
                array3[contador] = 3
            contador += 1


In [17]:
array3

array([2, 1, 2, 2, 2, 1, 3, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2,
       1, 2, 1, 2, 1, 2, 1, 1])

In [18]:
array3.reshape(2,3,5)

array([[[2, 1, 2, 2, 2],
        [1, 3, 1, 2, 1],
        [1, 2, 1, 1, 2]],

       [[1, 1, 2, 1, 1],
        [1, 2, 1, 2, 1],
        [2, 1, 2, 1, 1]]])