# **Ejercicios de pair programming Módulo 2 Sprint 1**
## **NumPy: Lección 1**
### **Introducción a NumPy**

---

In [2]:
import numpy as np

1. Cread tres arrays: de una, dos y tres dimensiones.
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas en algunos casos.
    
    📌 Nota
    - El array de 2 dimensiones debe ser de 2 filas y 3 columnas
    - El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [3]:
unidimensional = np.random.randint(1,10, (3))
unidimensional

array([3, 3, 7])

In [4]:
bidimensional = np.random.randint(1,10, (2,3))
bidimensional

array([[4, 5, 5],
       [5, 3, 1]])

In [5]:
multidimensional = np.random.randint(1,10, (2,3,5))
multidimensional

array([[[4, 4, 4, 4, 1],
        [1, 9, 7, 6, 4],
        [4, 7, 2, 9, 4]],

       [[7, 9, 7, 4, 1],
        [4, 6, 1, 6, 3],
        [8, 8, 3, 5, 9]]])

2. Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [6]:

def propiedades_array(array): 
    """ _summary_ muestra las propiedades básicas de un array. 
        _args_ array
        Return propiedades del array"""

    print(array)
    return f"Tiene forma de {array.shape}, su tamaño es de {array.size} elemento/s, tiene {array.ndim} dimension/es y el tipo de dato que contiene es {array.dtype}"

In [7]:
propiedades_array(unidimensional)

[3 3 7]


'Tiene forma de (3,), su tamaño es de 3 elemento/s, tiene 1 dimension/es y el tipo de dato que contiene es int32'

In [8]:
propiedades_array(bidimensional)

[[4 5 5]
 [5 3 1]]


'Tiene forma de (2, 3), su tamaño es de 6 elemento/s, tiene 2 dimension/es y el tipo de dato que contiene es int32'

In [9]:
propiedades_array(multidimensional)

[[[4 4 4 4 1]
  [1 9 7 6 4]
  [4 7 2 9 4]]

 [[7 9 7 4 1]
  [4 6 1 6 3]
  [8 8 3 5 9]]]


'Tiene forma de (2, 3, 5), su tamaño es de 30 elemento/s, tiene 3 dimension/es y el tipo de dato que contiene es int32'

3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas.

In [10]:
matriz = np.identity(3)
matriz

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [11]:
matriz_unos = np.ones_like(multidimensional)
matriz_unos

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

5. Es el momento de hacer algunas operaciones entre arrays:
 - ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?


In [12]:
#No se pueden sumar porque no tienen la misma forma. Si no es así, no se puede operar entre arrays independientemente de las dimensiones. 

 - En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.


In [13]:
nueva_matriz = np.identity(3)
nueva_matriz

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
suma_matrices = np.add(matriz, nueva_matriz)
suma_matrices

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

 - Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.


In [15]:
mul_matrices = np.multiply(matriz, nueva_matriz)
mul_matrices

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 - Dividid las dos matrices

In [16]:
div_matrices = np.divide(matriz, nueva_matriz)
div_matrices

C:\Users\cbggb\AppData\Local\Temp\ipykernel_31108\1928110201.py:1: RuntimeWarning: invalid value encountered in divide
  div_matrices = np.divide(matriz, nueva_matriz)


array([[ 1., nan, nan],
       [nan,  1., nan],
       [nan, nan,  1.]])