# **Ejercicios de pair programming Módulo 2 Sprint 1**
## **NumPy: Lección 4**
### **Conjuntos y distribuciones aleatorias**

In [2]:
import numpy as np

1. ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [3]:
np.random.seed(1)
a1 = np.random.random_sample((2,4))
a1

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01]])

In [4]:
np.random.seed(1)
a2 = np.random.random_sample((2,4))
a2

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01]])

2. Cread los siguientes arrays:

- Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

- Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

In [8]:
uniforme = np.unique(np.random.uniform(0, 10, (2,3,5)).round())
uniforme


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [9]:
binomial = np.unique(np.random.binomial(10, 0.3, (2,3,5)))
binomial

array([0, 1, 2, 3, 4, 5, 6])

3. En esta lección hemos aprendido algunos métodos de teórias de conjuntos.
   Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:

- Elementos comunes entre los dos arrays


In [10]:
np.intersect1d(uniforme, binomial)
# Con esta operación hemos seleccionado todos los elementos que son comunes a los dos arrays.

array([0., 1., 2., 3., 4., 5., 6.])

- Unión de los dos arrays


In [11]:
np.union1d(uniforme, binomial)
#En esta operación hemos unido todos los elementos de los dos arrays y hemos eliminado los elementos duplicados.

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

- ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores   númericos


In [12]:
np.setdiff1d(uniforme, binomial)
#En esta operación hemos extraído los elementos que están en el array uniforme pero no estan presentes en el array binomial.

array([ 7.,  8.,  9., 10.])

    
⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?


4. Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.


In [14]:
array1 = np.random.randint(1, 100, (80))
array1

array([54, 48, 61, 35, 33, 20, 68, 25, 84, 95, 39, 48,  6, 80, 64, 88, 33,
       43, 75, 67, 89, 99, 31, 18, 69, 65, 61, 79, 18, 40, 36, 82, 29, 23,
       39, 42, 75, 78, 71, 26, 49, 51, 63, 45, 55,  1, 87, 17, 20, 10, 93,
       52, 11, 69, 24, 15, 64, 22, 47,  4, 57, 89, 81, 47, 55, 80, 72, 15,
       78, 16, 26, 54, 85, 59, 86, 30, 45, 38, 23, 92])

In [15]:
array2 = np.random.randint(1, 100, (80))
array2

array([55, 77, 13, 60, 27, 77, 72, 88, 40, 44, 77, 39, 92, 70, 99, 34, 44,
       27, 57, 70, 74, 53, 90, 28, 44,  2, 83, 95, 97, 27, 85, 31, 65, 23,
       99, 53,  4, 71, 13, 40, 84, 49, 62, 71, 14, 37, 24, 23, 67, 93, 96,
       54, 10, 42, 58, 89, 94, 77, 83, 12, 37, 17, 31, 85, 58, 36, 42, 82,
        3, 86, 94, 37, 47, 81, 28, 73, 29,  3, 14, 42])


- Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.


In [16]:
array1 = np.unique(array1)
array1

array([ 1,  4,  6, 10, 11, 15, 16, 17, 18, 20, 22, 23, 24, 25, 26, 29, 30,
       31, 33, 35, 36, 38, 39, 40, 42, 43, 45, 47, 48, 49, 51, 52, 54, 55,
       57, 59, 61, 63, 64, 65, 67, 68, 69, 71, 72, 75, 78, 79, 80, 81, 82,
       84, 85, 86, 87, 88, 89, 92, 93, 95, 99])

In [17]:
array2 = np.unique(array2)
array2

array([ 2,  3,  4, 10, 12, 13, 14, 17, 23, 24, 27, 28, 29, 31, 34, 36, 37,
       39, 40, 42, 44, 47, 49, 53, 54, 55, 57, 58, 60, 62, 65, 67, 70, 71,
       72, 73, 74, 77, 81, 82, 83, 84, 85, 86, 88, 89, 90, 92, 93, 94, 95,
       96, 97, 99])

- Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.


In [19]:
array3 = np.setdiff1d(array1, array2)
array3

array([ 1,  6, 11, 15, 16, 18, 20, 22, 25, 26, 30, 33, 35, 38, 43, 45, 48,
       51, 52, 59, 61, 63, 64, 68, 69, 75, 78, 79, 80, 87])

- Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.


In [20]:
array4 = np.setdiff1d(array2, array1)
array4

array([ 2,  3, 12, 13, 14, 27, 28, 34, 37, 44, 53, 58, 60, 62, 70, 73, 74,
       77, 83, 90, 94, 96, 97])

- Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.


In [22]:
array5 = np.intersect1d(array1, array2)
array5

array([ 4, 10, 17, 23, 24, 29, 31, 36, 39, 40, 42, 47, 49, 54, 55, 57, 65,
       67, 71, 72, 81, 82, 84, 85, 86, 88, 89, 92, 93, 95, 99])

- ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [24]:
print(len(array1))
print(len(array2))
print(len(array3))
print(len(array4))
print(len(array5))
print("_________")
print(len(array1) == len(array3) + len(array5))
print(len(array2) == len(array4) + len(array5))



61
54
30
23
31
_________
True
True
