# **Ejercicios de pair programming Módulo 2 Sprint 1**
## **NumPy: Lección 2**
### **Indexación**

In [2]:
import numpy as np

1. Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:

    - El valor de la primera fila y la segunda columna.
    - Los valores de la segunda fila y las dos primeras columnas.
    - Extraed las filas pares (incluyendo la 0) y todas las columnas.
    - Extraed los valores que sean mayores que 0.5.
    - Extraed los valores menores que 0.2 o mayores que 0.5

In [7]:
array = np.random.rand(5,3).round(2)
array

array([[0.51, 0.16, 0.08],
       [0.27, 0.23, 0.54],
       [0.06, 0.72, 0.91],
       [0.63, 0.37, 0.96],
       [0.66, 0.7 , 0.49]])

In [8]:
print(array[0, 1])
print("---")
print(array[1, :2])
print("---")
print(array[::2, :])
print("---")
print(array[array > 0.5])
print("---")
print(array[(array < 0.2) | (array > 0.5)])

0.16
---
[0.27 0.23]
---
[[0.51 0.16 0.08]
 [0.06 0.72 0.91]
 [0.66 0.7  0.49]]
---
[0.51 0.54 0.72 0.91 0.63 0.96 0.66 0.7 ]
---
[0.51 0.16 0.08 0.54 0.06 0.72 0.91 0.63 0.96 0.66 0.7 ]


2. Cread dos array de tres dimensiones:

    - El primero de 2 matrices, 5 filas y 3 columnas.
    - El segundo de 3 matrices, 2 filas y 5 columnas.


In [11]:
tridim1 = np.random.randint(0, 50, (2,5,3))
tridim1

array([[[12, 16, 36],
        [ 2,  0,  5],
        [47, 32, 35],
        [10, 36, 37],
        [18, 19,  1]],

       [[ 2, 43, 31],
        [ 3,  7, 37],
        [ 8, 22, 19],
        [39, 43, 37],
        [21, 29,  9]]])

In [10]:
tridim2 = np.random.randint(0, 50, (3,2,5))
tridim2

array([[[27, 29, 21,  1, 33],
        [35, 15, 44, 28, 32]],

       [[20, 45, 32, 30, 19],
        [12, 17, 25, 35,  3]],

       [[49, 26, 26,  4, 19],
        [30, 34, 12, 28, 44]]])

- Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.


In [12]:

def propiedades_array(array): 
    """ Esta función devuelve las propiedades de un array que se pasa como parámetro"""

    print(array)
    return f"Tiene forma de {array.shape}, su tamaño es de {array.size} elemento/s, tiene {array.ndim} dimension/es y el tipo de dato que contiene es {array.dtype}"

In [13]:
propiedades_array(tridim1)

[[[12 16 36]
  [ 2  0  5]
  [47 32 35]
  [10 36 37]
  [18 19  1]]

 [[ 2 43 31]
  [ 3  7 37]
  [ 8 22 19]
  [39 43 37]
  [21 29  9]]]


'Tiene forma de (2, 5, 3), su tamaño es de 30 elemento/s, tiene 3 dimension/es y el tipo de dato que contiene es int64'

In [14]:
propiedades_array(tridim2)

[[[27 29 21  1 33]
  [35 15 44 28 32]]

 [[20 45 32 30 19]
  [12 17 25 35  3]]

 [[49 26 26  4 19]
  [30 34 12 28 44]]]


'Tiene forma de (3, 2, 5), su tamaño es de 30 elemento/s, tiene 3 dimension/es y el tipo de dato que contiene es int64'

- Sumad los dos arrays. ¿Podéis? ¿Por qué?


In [17]:
suma = np.add(tridim1, tridim2)
#No nos permite hacer la suma porque no tienen la misma forma.

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

- Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:

    .reshape()
    .transpose()

        
- Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [18]:
nuevo_tridim1 = np.transpose(tridim1, (2,0,1))
nuevo_tridim1

array([[[12,  2, 47, 10, 18],
        [ 2,  3,  8, 39, 21]],

       [[16,  0, 32, 36, 19],
        [43,  7, 22, 43, 29]],

       [[36,  5, 35, 37,  1],
        [31, 37, 19, 37,  9]]])

In [22]:
suma2 = np.add(nuevo_tridim1, tridim2)
suma2


array([[[39, 31, 68, 11, 51],
        [37, 18, 52, 67, 53]],

       [[36, 45, 64, 66, 38],
        [55, 24, 47, 78, 32]],

       [[85, 31, 61, 41, 20],
        [61, 71, 31, 65, 53]]])

In [21]:
nuevo_tridim2 = np.reshape(tridim2, (2,5,3))
nuevo_tridim2

array([[[27, 29, 21],
        [ 1, 33, 35],
        [15, 44, 28],
        [32, 20, 45],
        [32, 30, 19]],

       [[12, 17, 25],
        [35,  3, 49],
        [26, 26,  4],
        [19, 30, 34],
        [12, 28, 44]]])

In [23]:
suma3 = np.add(nuevo_tridim2, tridim1)
suma3


array([[[39, 45, 57],
        [ 3, 33, 40],
        [62, 76, 63],
        [42, 56, 82],
        [50, 49, 20]],

       [[14, 60, 56],
        [38, 10, 86],
        [34, 48, 23],
        [58, 73, 71],
        [33, 57, 53]]])